spring.application.name=amazon_event
server.port=9999
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#spring.data.mongodb.auto-index-creation=true

##spring.data.mongodb.uri=mongodb+srv://admin:cTuZyQko7SlLhkuB@cluster0.13tr3po.mongodb.net/Cluster0?retryWrites=true&w=majority
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=demo

logging.level.org.springframework.data.mongodb.repository.Query=trace

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

